### ISSUE TITLE
Automatically crashes

### ISSUE THREAD

**Issue by tom11298** [artnc/chronofile#11]
Android version 13, 

I have been having using the app for over 2 years now, it works great. Today, it started not opening, or closing when it opens, I tried reinstalling, rebooting my phone, etc
No luck

**Comment by artnc** [comment]
Wow that's dedication! Sorry to hear you're having trouble. Did you update your phone recently? The app still works for me on Android 13 on both an emulator and my real device.

If you happen to be comfortable using Android Studio, could you try opening the app with your phone attached and see what shows up in Logcat?

**Comment by tom11298** [comment]
Hi Art,

I really appreciate the super quick response, my apologies for not getting
back to you. I am not in any way comfortable using Android Studio, I am
however in engineering and will figure it out, I have a foundation of C,
C++, and Python, but Android apps are all a bit new to me. Do you have any
tutorials you suggest to get started with? I have been very busy recently
but in September I will have some more time to investigate for myself.

I have tried deleting all the files and re downloading your app but this
didn't change anything.
I have a Pixel 5, and this started not long before I sent you the first
message, however my phone got stuck in a boot loop, I don't know what,
however since then your app crashes when opened.

Thank you very much for your help,

Thomas Leclaire
Process and Product Engineering, Raufoss Neuman
President, Oxford Universities Motorsport Foundation
Oxford Brookes University, Motorsport Engineering

**Comment by artnc** [comment]
Thanks for your willingness to help troubleshoot this! An easier method than Android Studio might be Android's built-in bug reporting system, which should take just a few minutes:

1. Try opening Chronofile a few times to trigger the crash
1. Follow [these instructions](https://support.avast.com/en-ww/article/create-android-bug-report/#mac) to create a full bug report
1. Instead of sending the bug report to Avast, send it to me. My email address can be found at the bottom of my [website](https://chaidarun.com/about):

<img width="372" alt="Screenshot 2023-08-13 at 21 22 46" src="https://github.com/artnc/chronofile/assets/2595572/83e71642-ed20-4da6-b8aa-d3b35b33b296">

**Comment by artnc** [comment]
Resolved over email - somehow the `chronofile.tsv` and/or `chronofile.json` data files got corrupted, and deleting them allowed the app to work normally again
